application: ie6eliminator
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: init.py
